<template>
    <v-container>
        <h1 class="font-weight-light">
            peptfilter
        </h1>
        <h3 class="font-weight-light">
            Filters peptides based on length and amino acid occurrence.
        </h3>

        <v-divider class="my-2" />

        <p>
            The <inline-code>peptfilter</inline-code> command takes one or more (tryptic) peptides as input and returns them as output if they satisfy all filter criteria.
            By default, peptides with length between 5 and 50 are retained. This command runs entirely locally and doesn't connect to any server.
        </p>

        <header-body-card
            id="input"
            title="Input"
            large-title
        >
            <p>
                The <inline-code>peptfilter</inline-code> command accepts (tryptic) peptides as input from <i>standard input</i>. A single peptide per line is expected.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>AAR
                <br>AALTER
                <br><sentinel>$</sentinel> cat input.txt | peptfilter
                <br>AALTER
            </boxed>
        </header-body-card>

        <header-body-card
            id="output"
            title="Output"
            class="mt-5"
            large-title
        >
            <p>
                The <inline-code>peptfilter</inline-code> command outputs all input peptides that satisfy all filter criteria to <i>standard output</i>. By default, peptides
                with a length lower than 5 or higher than 50 are removed. The length filter can be changed by using the <r-link
                    to="#options"
                    router
                >
                    --minlen
                </r-link>
                and <r-link
                    to="#options"
                    router
                >
                    --maxlen
                </r-link> parameters. Peptides can also be filtered based on whether or not they lack or contain certain amino
                acids. This can be done with the <r-link
                    to="#options"
                    router
                >
                    --lacks
                </r-link> and <r-link
                    to="#options"
                    router
                >
                    --contains
                </r-link> parameters.
            </p>
        </header-body-card>

        <header-body-card
            id="fasta"
            title="Fasta support"
            class="mt-5"
            large-title
        >
            <p>
                The <inline-code>peptfilter</inline-code> command supports input in a fasta-like format (for example generated by the <r-link
                    to="/clidocs/prot2pept"
                    router
                >
                    prot2pept command
                </r-link>).
                This format consists of a fasta header (a line starting with a >), followed by one or more lines containing one peptide each. When this format is detected,
                the fasta headers will automatically be included in the output.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>> header 1
                <br>AALTER
                <br>AAR
                <br>LGAALGAGLAVIGAGIGIGK
                <br>> header 2
                <br>PEPTIDE
                <br><sentinel>$</sentinel> cat intput.txt | peptfilter
                <br>> header 1
                <br>AALTER
                <br>LGAALGAGLAVIGAGIGIGK
                <br>> header 2
                <br>PEPTIDE
            </boxed>
        </header-body-card>

        <header-body-card
            id="options"
            title="Command-line options"
            class="mt-5"
            large-title
        >
            <h2>--minlen <span class="text-caption grey--text text--darken-2">Specify minimum length</span></h2>

            <p>
                By default, only peptides with a minimal length of 5 are retained. By using the <inline-code>--minlen</inline-code> parameter, this value can be changed.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>AALTER
                <br>AAR
                <br><sentinel>$</sentinel> cat input.txt | peptfilter <b>--minlen</b> 3
                <br>AALTER
                <br>AAR
            </boxed>

            <h2>--maxlen <span class="text-caption grey--text text--darken-2">Specify maximum length</span></h2>

            <p>
                By default, only peptides with a maximal length of 50 are retained. By using the <inline-code>--maxlen</inline-code> parameter, this value can be changed.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>AALTER
                <br>AAR
                <br><sentinel>$</sentinel> cat input.txt | peptfilter <b>--maxlen</b> 4
                <br>AAR
            </boxed>

            <h2>--contains / -c <span class="text-caption grey--text text--darken-2">Specify mandatory amino acids</span></h2>

            <p>
                By using the <inline-code>--contains</inline-code> parameter, you can specify the amino acids that a peptide must contain. All specified amino acids must be
                present in the peptide for it to be retained.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>AALTER
                <br>AARAAR
                <br><sentinel>$</sentinel> cat input.txt | peptfilter <b>--contains</b> RL
                <br>AALTER
            </boxed>

            <h2>--lacks / -l <span class="text-caption grey--text text--darken-2">Specify forbidden amino acids</span></h2>

            <p>
                By using the <inline-code>--lacks</inline-code> parameter, you can specify the amino acids that a peptide can not contain. The peptide may have none of the
                specified amino acids for it to be retained.
            </p>

            <h4>Example</h4>
            <boxed>
                <sentinel>$</sentinel> cat input.txt
                <br>AALTER
                <br>AARAAR
                <br><sentinel>$</sentinel> cat input.txt | peptfilter <b>--lacks</b> VL
                <br>AARAAR
            </boxed>

            <h2>--help / -h <span class="text-caption grey--text text--darken-2">Display help</span></h2>

            <p>
                This flag displays the help.
            </p>
        </header-body-card>
    </v-container>
</template>

<script setup lang="ts">
import InlineCode from '@/components/highlights/InlineCode.vue';
import HeaderBodyCard from '@/components/cards/HeaderBodyCard.vue';
import Boxed from '@/components/highlights/Boxed.vue';
import Sentinel from '@/components/highlights/Sentinel.vue';
import RLink from '@/components/highlights/ResourceLink.vue';
</script>
