AllCops:
  Include:
    - ''
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'bin/setup'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

# disable for now
Lint/NestedMethodDefinition:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/PredicateName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
