<template>
    <v-container>
        <h1 class="font-weight-light">
            Case Study: configuring a metagenomics pipeline
        </h1>
        <h3 class="font-weight-light">
            This case study shows how to use <Initialism>UMGAP</Initialism> for the taxonomic analysis of a metagenomics dataset.
        </h3>

        <HeaderBodyCard class="mt-5" title="Introduction">
            <p>
                The Unipept Metagenomics Analysis Pipeline (<Initialism>UMGAP</Initialism>) is a tool for mapping (short) metagenomics 
                reads to taxa, rivalling state of the art alternatives such as Kraken (2014) with the additional benefit of species 
                level identification. <Initialism>UMGAP</Initialism> achieves this by transforming the mapping task into a metaproteomics 
                problem by using various alternative gene predictors on the metagenomics reads and processing the resulting data with the 
                existing Unipept Metaproteomics Analysis Pipeline. Each step in <Initialism>UMGAP</Initialism> is highly configurable.
            </p>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Preprocessing">
            <p>
                Throughout this overview of <Initialism>UMGAP</Initialism>, all steps will have examples to demonstrate the exact usage. 
                For this, we have sampled 100 paired-end DNA reads from a dataset generated by {{ references.lindgreen.short }} for their 
                metabenchmark. As this dataset contains paired-end reads in <Initialism>FASTQ</Initialism> format, and <Initialism>UMGAP</Initialism> 
                operates on <Initialism>FASTA</Initialism> data, we perform a first preprocessing step to convert the <Initialism>FASTQ</Initialism> 
                into <Initialism>FASTA</Initialism> files. You can download these files to get the same results: <RLink to="/A1.fq" target="_blank">A1.fq</RLink> 
                and <RLink to="/A2.fq" target="_blank">A2.fq</RLink>.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap fastq2fasta A1.fq A2.fq | tee preprocessed.fa
                <br>>read1/1
                <br>ATCGCGCACGCGGCCGATGCCCCAGAAGAGATTGACAGCGGTGGGGCGGGCGGCGGCGAGGTGGTCGCAGATCTCGGCGACCTCTGCGTTGAGGGTCGGG
                <br>>read1/2
                <br>AAGATGGCGACTGGATGATGATCGCGCGGCAGGCCACCATCTACGATCCCGCAGTGAAGCATTACTAACCATGATGCGCAACGACTCGCTGTCAGAGCTA
                <br>>read2/1
                <br>AGATTGCTGGTGCGGGTGCTCTGCCGGGCTTCTTCATCTCGGACCGCGCATCCGATGCGCACACGGCACAGTAGGTATGCGGTGAGAGCACCTCGCTTTT
                <br>>read2/2
                <br>CGCAATCTTGCGGCGCACCGCGATCAAATCGGGATAGTCCGGTGTGTAACGCGTGCTCAGGTCATCTGCCCGTACCCGCAATACATTCAACTGTGTTTTA
                <br>>read3/1
                <br>CCCTCAAGCCCGATCGAACTTTCCTACTGCCCGACCTCAGCGCGGAGCATTACCGAATCGTCGTCAACAATCTCCCCGATGGCTTCTATGTGAACTCCAT
                <br>>read3/2
                <br>CAAAATGGAGTGGGCGCTACTGCTCCGTGAGCAGGGTCAGTTGGAGGGATTGGGGCGTGCGCTCGGGGATGCTAATGGCGGTGCCCCTGGATTCCTGAGA
            </Boxed>

            <p>
                This command will interleave the given <Initialism>FASTQ</Initialism> files and output a <Initialism>FASTA</Initialism> 
                stream, in which the paired-ends alternate each other.
            </p>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Protein translation">
            <p>
                To convert the metagenomics reads into a metaproteomics problem, we need to translate the <Initialism>DNA</Initialism> 
                fragments into protein fragments. While any gene prediction tool can be used, <Initialism>UMGAP</Initialism> was tested 
                with FragGeneScan (2010) and FragGeneScan++, our in-house improved version of FragGeneScanPlus (2015), a predictor using 
                Hidden Markov Models. Alternatively, you can also try all possible translations and use the built-in six-frame 
                translation tool.
            </p>

            <p>
                Using gene prediction limits our tool to the coding regions of the given DNA reads. This limit caps the sensitivity of 
                our predictions, as we can offer no prediction for a read from a non-coding region. On the other hand, coding regions are 
                more conserved and the mutations that do occur often do not change the resulting amino acid.
            </p>

            <p>
                For more information about the available options for the gene predictors, the FragGeneScan and FragGeneScan++ commands, 
                we refer to the <RLink to="http://omics.informatics.indiana.edu/FragGeneScan/">FragGeneScan</RLink> and 
                <RLink to="https://github.com/unipept/FragGeneScanPlusPlus">FragGeneScan++</RLink> documentation. Here, it suffices to 
                say that the commands below will write the predicted genes in <Initialism>FASTA</Initialism> format to a file called 
                `predicted-genes.faa`.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> FGS -s preprocessed.fa -o predicted-genes -w0 -t illumina_10 -p 16 > /dev/null
                <br><Sentinel>$</Sentinel> rm predicted-genes.fnn predicted-genes.out # we don't use these files
            </Boxed>

            <Boxed>
                <Sentinel>$</Sentinel> FGSpp -s stdin -o stdout -w 0 -r train -t illumina_10 -p 16 -m 3000 &lt; preprocessed.fa | tee predicted-genes.faa
            </Boxed>

            <p>
                With our alternative six-frame translation option, we choose to translate all (<Code>-a</Code>) frames using the standard 
                translation table.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap translate -a &lt; preprocessed.fa | tee predicted-genes.faa
                <br>>read1/1|1
                <br>IAHAADAPEEIDSGGAGGGEVVADLGDLCVEGR
                <br>>read1/1|2
                <br>SRTRPMPQKRLTAVGRAAARWSQISATSALRVG
                <br>>read1/1|3
                <br>RARGRCPRRD*QRWGGRRRGGRRSRRPLR*GS
                <br>>read1/1|1R
                <br>PDPQRRGRRDLRPPRRRPPHRCQSLLGHRPRAR
                <br>>read1/1|2R
                <br>PTLNAEVAEICDHLAAARPTAVNLFWGIGRVRD
                <br>>read1/1|3R
                <br>RPSTQRSPRSATTSPPPAPPLSISSGASAACA
                <br>>read1/2|1
                <br>KMATG**SRGRPPSTIPQ*SITNHDAQRLAVRA
                <br>>read1/2|2
                <br>RWRLDDDRAAGHHLRSRSEALLTMMRNDSLSEL
                <br>>read1/2|3
                <br>DGDWMMIARQATIYDPAVKHY*P*CATTRCQS
                <br>>read1/2|1R
                <br>*L*QRVVAHHG**CFTAGS*MVACRAIIIQSPS
                <br>>read1/2|2R
                <br>SSDSESLRIMVSNASLRDRRWWPAARSSSSRHL
                <br>>read1/2|3R
                <br>ALTASRCASWLVMLHCGIVDGGLPRDHHPVAI
                <br>>read2/1|1
                <br>RLLVRVLCRASSSRTAHPMRTRHSRYAVRAPRF
                <br>>read2/1|2
                <br>DCWCGCSAGLLHLGPRIRCAHGTVGMR*EHLAF
                <br>>read2/1|3
                <br>IAGAGALPGFFISDRASDAHTAQ*VCGESTSL
                <br>>read2/1|1R
                <br>KSEVLSPHTYCAVCASDARSEMKKPGRAPAPAI
                <br>>read2/1|2R
                <br>KARCSHRIPTVPCAHRMRGPR*RSPAEHPHQQS
                <br>>read2/1|3R
                <br>KRGALTAYLLCRVRIGCAVRDEEARQSTRTSN
                <br>>read2/2|1
                <br>RNLAAHRDQIGIVRCVTRAQVICPYPQYIQLCF
                <br>>read2/2|2
                <br>AILRRTAIKSG*SGV*RVLRSSARTRNTFNCVL
                <br>>read2/2|3
                <br>QSCGAPRSNRDSPVCNACSGHLPVPAIHSTVF
                <br>>read2/2|1R
                <br>*NTVECIAGTGR*PEHALHTGLSRFDRGAPQDC
                <br>>read2/2|2R
                <br>KTQLNVLRVRADDLSTRYTPDYPDLIAVRRKIA
                <br>>read2/2|3R
                <br>KHS*MYCGYGQMT*ARVTHRTIPI*SRCAARL
                <br>>read3/1|1
                <br>PSSPIELSYCPTSARSITESSSTISPMASM*TP
                <br>>read3/1|2
                <br>PQARSNFPTARPQRGALPNRRQQSPRWLLCELH
                <br>>read3/1|3
                <br>LKPDRTFLLPDLSAEHYRIVVNNLPDGFYVNS
                <br>>read3/1|1R
                <br>MEFT*KPSGRLLTTIR*CSALRSGSRKVRSGLR
                <br>>read3/1|2R
                <br>WSSHRSHRGDC*RRFGNAPR*GRAVGKFDRA*G
                <br>>read3/1|3R
                <br>GVHIEAIGEIVDDDSVMLRAEVGQ*ESSIGLE
                <br>>read3/2|1
                <br>QNGVGATAP*AGSVGGIGACARGC*WRCPWIPE
                <br>>read3/2|2
                <br>KMEWALLLREQGQLEGLGRALGDANGGAPGFLR
                <br>>read3/2|3
                <br>KWSGRYCSVSRVSWRDWGVRSGMLMAVPLDS*
                <br>>read3/2|1R
                <br>SQESRGTAISIPERTPQSLQLTLLTEQ*RPLHF
                <br>>read3/2|2R
                <br>LRNPGAPPLASPSARPNPSN*PCSRSSSAHSIL
                <br>>read3/2|3R
                <br>SGIQGHRH*HPRAHAPIPPTDPAHGAVAPTPF
            </Boxed>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Peptide profiling">
            <p>
                <Initialism>UMGAP</Initialism> uses exact substring matching to identify reads. The next step of the pipeline fragments 
                each amino acid sequence into 9-mers. The k-mers of a string are all possible substrings of length k. For example, the 
                4-mers of the string <Initialism>ABCDEFG</Initialism> are <Initialism>ABCD</Initialism>, <Initialism>BCDE</Initialism>, 
                <Initialism>CDEF</Initialism> and <Initialism>DEFG</Initialism>. After constructing all possible 9-mers, they are 
                matched against our index. This index maps each 9-mer encountered in the UniProt's protein knowledgebase (2014) to the 
                lowest common ancestor (<Initialism>LCA</Initialism>) of all the organisms it occured in. The <Initialism>LCA</Initialism> 
                of a set of taxa is equal to the taxon of the most specific rank in the <Initialism>NCBI</Initialism> taxonomy (2011) that 
                is either a descendant or an ancestor of all taxa in that set.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap prot2kmer2lca -o -k9 9-mer.index &lt; predicted-genes.faa | tee found-kmers.fa
                <br>>read1/1|1
                <br>0 0 0 0 0 0 0 0 0 0 35725 2759 1 1 1 2 515393 201174 0 1 0 0 0 379 0
                <br>>read1/1|2
                <br>0 0 0 0 0 0 0 0 0 1185650 1185650 140110 0 0 0 0 0 0 0 0 0 36842 0 1 162425
                <br>>read1/1|3
                <br>0 0 0 0 0 0 0 0 0 0 0 1773 47855 4530 1 1 1 1 1 0 35708 0 0 0
                <br>>read1/1|1R
                <br>0 0 0 0 2235 0 0 0 0 40674 1 1 2759 0 0 0 0 0 0 0 0 0 0 0 88724
                <br>>read1/1|2R
                <br>1 940557 1 940615 940615 940615 940615 940615 0 0 0 0 56 2 1 1 1 1 2 2 940615 940615 940615 940615 940615
                <br>>read1/1|3R
                <br>0 0 0 0 1036719 2 2759 0 2 1 1 1 2759 1 1 3916 3916 1760 0 237 1 2759 1 0
                <br>>read1/2|1
                <br>0 0 0 0 0 0 0 5627 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
                <br>>read1/2|2
                <br>0 52226 53355 1760 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 44471
                <br>>read1/2|3
                <br>940615 940615 940615 940615 940615 204434 204434 204434 204434 2 204434 204434 204434 0 0 0 0 0 0 0 0 0 0 0
                <br>>read1/2|1R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read1/2|2R
                <br>1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 4751 35708
                <br>>read1/2|3R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/1|1
                <br>0 1813 546364 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/1|2
                <br>0 68786 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/1|3
                <br>2 392734 392734 392734 392734 0 0 0 0 0 0 0 0 0 392734 0 0 0 0 0 0 0 0 0
                <br>>read2/1|1R
                <br>0 0 0 0 0 0 0 0 36740 0 0 0 0 0 0 0 0 0 0 0 0 0 379 379 0
                <br>>read2/1|2R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/1|3R
                <br>0 0 0 0 393310 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/2|1
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/2|2
                <br>1534 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/2|3
                <br>0 0 0 0 0 0 0 0 0 0 0 0 1370023 0 0 0 0 0 0 0 0 0 0 0
                <br>>read2/2|1R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 488447 0 0 0 0 0 0 0
                <br>>read2/2|2R
                <br>0 0 0 0 0 0 33882 4930 4930 0 392734 1 392734 392734 392734 392734 392734 392734 392734 392734 392733 392733 392733 392733 392734
                <br>>read2/2|3R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read3/1|1
                <br>0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1754192 0 6282 0 7164 0 0 0 0 0
                <br>>read3/1|2
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read3/1|3
                <br>332163 332163 332163 2 1 332163 2 332163 332163 332163 332163 332163 1 332163 332163 332163 332163 332163 332163 332163 332163 332163 0 0
                <br>>read3/1|1R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 322865 7868 0 0 0 0 0 0
                <br>>read3/1|2R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read3/1|3R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
                <br>>read3/2|1
                <br>0 0 0 0 0 0 0 0 0 0 632569 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                <br>>read3/2|2
                <br>0 0 0 8839 0 0 40754 0 0 0 0 323415 0 286 1 1760 0 0 0 0 0 0 0 0 0
                <br>>read3/2|3
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 28216 0 0 0 0 0 0 0
                <br>>read3/2|1R
                <br>332163 2 2 332163 332163 332163 332163 332163 332163 332163 1 332163 332163 332163 2 2 1 332163 332163 0 0 0 0 0 0
                <br>>read3/2|2R
                <br>67819 0 0 0 5855 1 1 2 519963 5206 0 1245748 0 0 0 0 0 0 0 0 0 101127 0 0 0
                <br>>read3/2|3R
                <br>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13687 0 0 0
            </Boxed>

            <p>
                This command will look up each 9-mer in the input data and output the associated taxon if any is found. With the 
                <Code>-o</Code> or <Code>--one-on-one</Code> flag, the unrecognized 9-mers will be included as a "0" taxon, the use of 
                which will be clarified in the next step. Note: the real output would contain newlines between taxa, which have been 
                replaced here by spaces for readability.
            </p>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="(Optional) Filtering">
            <p>
                Especially when running the pipeline with all six frames, a lot of the translations are invalid since we expect only one 
                of the reading frames, rarely more, to yield a valid protein. The Seed-Extend step in the pipeline filters out most 
                random hits by selecting only 9-mer hits which are spatially close to other hits.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap seedextend &lt; found-kmers.fa | tee selected-seeds.fa
                <br>>read1/1|1
                <br>35725 2759 1 1 1 2 515393 201174
                <br>>read1/1|2
                <br>1185650 1185650 140110
                <br>>read1/1|3
                <br>1773 47855 4530 1 1 1 1 1
                <br>>read1/1|1R
                <br>40674 1 1 2759
                <br>>read1/1|2R
                <br>1 940557 1 940615 940615 940615 940615 940615 56 2 1 1 1 1 2 2 940615 940615 940615 940615 940615
                <br>>read1/1|3R
                <br>2 1 1 1 2759 1 1 3916 3916 1760
                <br>>read1/2|1
                <br>
                <br>>read1/2|2
                <br>
                <br>>read1/2|3
                <br>940615 940615 940615 940615 940615 204434 204434 204434 204434 2 204434 204434 204434
                <br>>read1/2|1R
                <br>
                <br>>read1/2|2R
                <br>
                <br>>read1/2|3R
                <br>
                <br>>read2/1|1
                <br>
                <br>>read2/1|2
                <br>
                <br>>read2/1|3
                <br>2 392734 392734 392734 392734
                <br>>read2/1|1R
                <br>379 379
                <br>>read2/1|2R
                <br>
                <br>>read2/1|3R
                <br>
                <br>>read2/2|1
                <br>
                <br>>read2/2|2
                <br>
                <br>>read2/2|3
                <br>
                <br>>read2/2|1R
                <br>
                <br>>read2/2|2R
                <br>33882 4930 4930 392734 1 392734 392734 392734 392734 392734 392734 392734 392734 392733 392733 392733 392733 392734
                <br>>read2/2|3R
                <br>
                <br>>read3/1|1
                <br>
                <br>>read3/1|2
                <br>
                <br>>read3/1|3
                <br>332163 332163 332163 2 1 332163 2 332163 332163 332163 332163 332163 1 332163 332163 332163 332163 332163 332163 332163 332163 332163
                <br>>read3/1|1R
                <br>
                <br>>read3/1|2R
                <br>
                <br>>read3/1|3R
                <br>
                <br>>read3/2|1
                <br>
                <br>>read3/2|2
                <br>
                <br>>read3/2|3
                <br>
                <br>>read3/2|1R
                <br>332163 2 2 332163 332163 332163 332163 332163 332163 332163 1 332163 332163 332163 2 2 1 332163 332163
                <br>>read3/2|2R
                <br>5855 1 1 2 519963 5206
                <br>>read3/2|3R
            </Boxed>

            <p>
                Note: the real output would contain newlines between taxa, which have been replaced here by spaces for readability.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> mv selected-seeds.fa found-kmers.fa # optional step, same format
            </Boxed>

            <p>
                The Seed-Extend algorithm requires spatial information which is provided by supplying the <Code>-o</Code> flag to the 
                previous command. The <Code>taxons.tsv</Code> is a file describing the <Initialism>NCBI</Initialism> taxonomic tree.
            </p>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Aggregation">
            <p>
                At this step of the pipeline, we have a list of taxon identifiers per protein, one protein per reading frame, 6 reading 
                frames per paired-end and 2 paired-ends per metagenomics read. To get a single taxon identification per read, we need to 
                aggregate these 12 lists. <Initialism>UMGAP</Initialism> offers 3 alternative aggregation strategies with varying speciality.
            </p>

            <ul>
                <li>
                    Unipept's lowest common ancestor strategy (<Initialism>LCA</Initialism>*), where the consensus taxon is, as before, 
                    the taxon of most specific rank which is either descendant or ancestor of every given taxon.
                </li>
                <li>
                    Kraken's maximum root-to-leaf path (<Initialism>MRTL</Initialism>), where the consensus taxon is the taxon in the 
                    given list which has the most ancestors in the given list.
                </li>
                <li>
                    A newly developed hybrid strategy, which combines <Initialism>LCA</Initialism>* and <Initialism>MRTL</Initialism> 
                    based on a given scaling factor (default 0.25). The hybrid method aims to ignore some outliers without compromising 
                    generality. This strategy is the default and will therefore be used below.
                </li>
            </ul>

            <p>
                Before aggregating the results per read, we remove the markers from the headers with <Code>sed</Code> and combine the 
                results of each reading frame and paired-end with <Code>uniq</Code>.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> sed '/^>/s_/.*__' found-kmers.fa | umgap uniq | umgap taxa2agg taxons.tsv | tee classification.fa
                <br>>read1
                <br>940615
                <br>>read2
                <br>392734
                <br>>read3
                <br>332163
            </Boxed>
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Visualisation">
            <p>
                Now that we have the results of our analysis, we'd like to visualise them. A frequency table and interactive 
                visualisations are available as the <Code>taxa2freq</Code> and <Code>taxa2tree</Code> commands. The first shows the 
                number of reads mapping to each taxon in <Initialism>CSV</Initialism> format, easily imported in other programs.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap taxa2freq -r species taxons.tsv &lt; classification.fa | tee report.csv
                <br>taxon id,taxon name,stdin
                <br>332163,Candidatus Solibacter usitatus,1
                <br>392734,Terriglobus roseus,1
                <br>940615,Granulicella tundricola,1
            </Boxed>

            <p>
                The <Code>taxa2freq</Code> command to snap each taxon to either a species or root (unknown) and report the frequency table 
                of the results.
            </p>

            <p>
                The <Code>taxa2tree</Code> command will send the results to the Unipept webserver, where an interactive 
                <Initialism>HTML</Initialism>-visualisation will be created. The webpage can either be saved to a file, or you can 
                request a shareable <Initialism>URL</Initialism> with --url.
            </p>

            <Boxed>
                <Sentinel>$</Sentinel> umgap taxa2tree --url &lt; classification.fa
                <br><RLink to="https://bl.ocks.org/5960ffd859fb17439d7975896f513bc3">https://bl.ocks.org/5960ffd859fb17439d7975896f513bc3</RLink>
            </Boxed>

            <ImageCaptionCard class="mt-5" :image="require('@/assets/documentation/metagenomics/casestudy-umgap-advanced.png')" />
        </HeaderBodyCard>

        <HeaderBodyCard class="mt-5" title="Recap">
            <p>
                The complete <Initialism>UMGAP</Initialism> can be written as a single command. This allows the steps to run in parallel, 
                further speeding up the final result.
            </p>

            <Boxed>
<pre>
<Sentinel>$</Sentinel> umgap fastq2fasta A1.fq A2.fq |          # joining paired-end files
  umgap translate -a |                     # translating all six frames
  umgap prot2kmer2lca -o -k9 9-mer.index | # mapping each 9-mer onto a taxon or 0
  umgap seedextend |                       # filtering extended seeds
  sed '/^>/s_/.*__' |                      # dropping the paired-end and frame annotations
  umgap uniq |                             # joining equal headers (all taxa of the same read)
  umgap taxa2agg taxons.tsv |              # aggregating all taxa
  grep -v '^>' |                           # dropping headers
  umgap taxa2freq taxons.tsv               # make frequency table
taxon id,taxon name,stdin
332163,Candidatus Solibacter usitatus,1
392734,Terriglobus roseus,1
940615,Granulicella tundricola,1
</pre>
            </Boxed>

            <p>
                This command processes the complete Metabenchmark A1 dataset containing 116 million paired-end reads in a VM 
                (8 cores, 200GB RAM) on our computational server (16 Intel Xeon CPU E5-2650 v2 at 2.60GHz, 20*16GB RDIMM x4 Data Width 
                at 1866MHz, with the 9-mer index loaded in RAM) in 4h22, that is 1840 (paired-end) reads per second. Using FragGeneScan++ 
                speeds this up to 10100 reads per second.
            </p>
        </HeaderBodyCard>

        <h2 class="font-weight-light mt-5">References</h2>
        <ul>
            <li v-for="reference in references" :key="reference.short">
                {{ reference.full }}
            </li>
        </ul>
    </v-container>
</template>

<script setup lang="ts">
import HeaderBodyCard from '@/components/cards/HeaderBodyCard.vue';
import RLink from '@/components/highlights/ResourceLink.vue';
import Boxed from '@/components/highlights/Boxed.vue';
import Sentinel from '@/components/highlights/Sentinel.vue';
import Code from '@/components/highlights/InlineCode.vue';
import Initialism from '@/components/highlights/Initialism.vue';
import ImageCaptionCard from '@/components/cards/ImageCaptionCard.vue';

const references = {
    wood: {
        full: "Wood, D. E., & Salzberg, S. L. (2014). Kraken: ultrafast metagenomic sequence classification using exact alignments. Genome biology, 15(3), R46.",
        short: ""
    },
    lindgreen: { 
        full: "Lindgreen, S., Adair, K. L., & Gardner, P. P. (2016). An evaluation of the accuracy and speed of metagenome analysis tools. Scientific reports, 6, 19233.",
        short: "Lindgreen et al. (2016)"
    },
    rho: {
        full: "Rho, M., Tang, H., & Ye, Y. (2010). FragGeneScan: predicting genes in short and error-prone reads. Nucleic acids research, 38(20), e191-e191.",
        short: ""
    },
    kim: {
        full: "Kim, D., Hahn, A. S., Wu, S. J., Hanson, N. W., Konwar, K. M., & Hallam, S. J. (2015, August). FragGeneScan-Plus for scalable high-throughput short-read open reading frame prediction. Computational Intelligence in Bioinformatics and Computational Biology (CIBCB), 2015 IEEE Conference on (pp. 1-8), IEEE.",
        short: ""
    },
    uniprot: {
        full: "UniProt Consortium. (2014). UniProt: a hub for protein information. Nucleic acids research, 43(D1), D204-D212.",
        short: ""
    },
    federhen: {
        full: "Federhen, S. (2011). The NCBI taxonomy database. Nucleic acids research, 40(D1), D136-D143.",
        short: ""
    }
}
</script>

<style scoped>
li {
    line-height: 1.5 !important;
    padding-bottom: 8px;
}
</style>
