FROM ubuntu

LABEL maintainer="Pieter Verschaffelt <pieter.verschaffelt@ugent.be>"

RUN apt-get update
# We need java in this container
RUN apt-get install -y git openjdk-8-jdk mysql-client tofrodos


