name: Deploy Unipept Web

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Start deploying requested version
      run: |
        echo "deploy web $GITHUB_SHA" | ssh -p 4840 unipept@unipeptapi.ugent.be
